version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env

  mock-api:
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./mock-api:/app
      - /app/node_modules

  