---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Build and push frontend Docker image
      command:
        cmd: "docker buildx build --platform linux/amd64 -t gcr.io/weatherapp-eficode/weatherapp-frontend ../frontend --push"

    - name: Deploy frontend to Cloud Run
      command:
        cmd: "gcloud run deploy weatherapp-frontend --image gcr.io/weatherapp-eficode/weatherapp-frontend:latest --region europe-north1 --allow-unauthenticated"

    - name: Build and push backend Docker image
      command:
        cmd: "docker buildx build --platform linux/amd64 -t gcr.io/weatherapp-eficode/weatherapp-backend ../backend --push"

    - name: Deploy backend to Cloud Run
      command:
        cmd: "gcloud run deploy weatherapp-backend --image gcr.io/weatherapp-eficode/weatherapp-backend:latest --region europe-north1 --allow-unauthenticated"
